*** Variables ***
${REGISTER_LINK}    xpath=//a[text()="Register"]
${FIRST_NAME}   xpath=//input[@id="customer.firstName"]
${LAST_NAME}    xpath=//input[@id="customer.lastName"]
${ADDRESS}  xpath=//input[@name="customer.address.street"]
${CITY}   xpath=//input[@id="customer.address.city"]
${STATE}    xpath=//input[@id="customer.address.state"]
${ZIPCODE}  xpath=//input[@id="customer.address.zipCode"]
${PHONE}    xpath=//input[@id="customer.phoneNumber"]
${SSN}      xpath=//input[@id="customer.ssn"]
${USERNAME}   xpath=//input[@id="customer.username"]
${PASSWORD}     xpath=//input[@id="customer.password"]
${CONFIRM_PASSWORD}     xpath=//input[@id="repeatedPassword"]
${REGISTER_BTN}     xpath=//input[@value="Register"]